/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemContratoRouteImport } from './routes/sem-contrato'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecibosAssinadosListaRouteImport } from './routes/recibos-assinados-lista'
import { Route as RecibosAssinadosRouteImport } from './routes/recibos-assinados'
import { Route as LancamentoRouteImport } from './routes/lancamento'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as ControleOperacionalRouteImport } from './routes/controle-operacional'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const SemContratoRoute = SemContratoRouteImport.update({
  id: '/sem-contrato',
  path: '/sem-contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecibosAssinadosListaRoute = RecibosAssinadosListaRouteImport.update({
  id: '/recibos-assinados-lista',
  path: '/recibos-assinados-lista',
  getParentRoute: () => rootRouteImport,
} as any)
const RecibosAssinadosRoute = RecibosAssinadosRouteImport.update({
  id: '/recibos-assinados',
  path: '/recibos-assinados',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentoRoute = LancamentoRouteImport.update({
  id: '/lancamento',
  path: '/lancamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleOperacionalRoute = ControleOperacionalRouteImport.update({
  id: '/controle-operacional',
  path: '/controle-operacional',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/controle-operacional': typeof ControleOperacionalRoute
  '/indicadores': typeof IndicadoresRoute
  '/lancamento': typeof LancamentoRoute
  '/recibos-assinados': typeof RecibosAssinadosRoute
  '/recibos-assinados-lista': typeof RecibosAssinadosListaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sem-contrato': typeof SemContratoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/controle-operacional': typeof ControleOperacionalRoute
  '/indicadores': typeof IndicadoresRoute
  '/lancamento': typeof LancamentoRoute
  '/recibos-assinados': typeof RecibosAssinadosRoute
  '/recibos-assinados-lista': typeof RecibosAssinadosListaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sem-contrato': typeof SemContratoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/controle-operacional': typeof ControleOperacionalRoute
  '/indicadores': typeof IndicadoresRoute
  '/lancamento': typeof LancamentoRoute
  '/recibos-assinados': typeof RecibosAssinadosRoute
  '/recibos-assinados-lista': typeof RecibosAssinadosListaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sem-contrato': typeof SemContratoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/controle-operacional'
    | '/indicadores'
    | '/lancamento'
    | '/recibos-assinados'
    | '/recibos-assinados-lista'
    | '/reset-password'
    | '/sem-contrato'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/controle-operacional'
    | '/indicadores'
    | '/lancamento'
    | '/recibos-assinados'
    | '/recibos-assinados-lista'
    | '/reset-password'
    | '/sem-contrato'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/controle-operacional'
    | '/indicadores'
    | '/lancamento'
    | '/recibos-assinados'
    | '/recibos-assinados-lista'
    | '/reset-password'
    | '/sem-contrato'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ControleOperacionalRoute: typeof ControleOperacionalRoute
  IndicadoresRoute: typeof IndicadoresRoute
  LancamentoRoute: typeof LancamentoRoute
  RecibosAssinadosRoute: typeof RecibosAssinadosRoute
  RecibosAssinadosListaRoute: typeof RecibosAssinadosListaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SemContratoRoute: typeof SemContratoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sem-contrato': {
      id: '/sem-contrato'
      path: '/sem-contrato'
      fullPath: '/sem-contrato'
      preLoaderRoute: typeof SemContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibos-assinados-lista': {
      id: '/recibos-assinados-lista'
      path: '/recibos-assinados-lista'
      fullPath: '/recibos-assinados-lista'
      preLoaderRoute: typeof RecibosAssinadosListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibos-assinados': {
      id: '/recibos-assinados'
      path: '/recibos-assinados'
      fullPath: '/recibos-assinados'
      preLoaderRoute: typeof RecibosAssinadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamento': {
      id: '/lancamento'
      path: '/lancamento'
      fullPath: '/lancamento'
      preLoaderRoute: typeof LancamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle-operacional': {
      id: '/controle-operacional'
      path: '/controle-operacional'
      fullPath: '/controle-operacional'
      preLoaderRoute: typeof ControleOperacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ControleOperacionalRoute: ControleOperacionalRoute,
  IndicadoresRoute: IndicadoresRoute,
  LancamentoRoute: LancamentoRoute,
  RecibosAssinadosRoute: RecibosAssinadosRoute,
  RecibosAssinadosListaRoute: RecibosAssinadosListaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SemContratoRoute: SemContratoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
